### ISSUE TITLE
this doesn't demonstrate http2

### ISSUE THREAD

**Issue by jnorthrup** [AndreasKl/embedded-jetty-http2#1]
[INFO] jetty-9.3.7.v20160115
[INFO] Started o.e.j.m.p.JettyWebAppContext@1f2d2181{/,file:///C:/Users/jim/IdeaProjects/kbrprime-pwa/embedded-jetty-http2-master/target/webapp-tmp/,AVAILABLE}{file:///C:/Users/jim/IdeaProjects/kbrprime-pwa/embedded-jetty-http2-master/target/webapp-tmp/}
[INFO] Started ServerConnector@6443b128{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Started @2592ms
[INFO] Started Jetty Server

can you finish the example?  the ssl-constructor  has some showstoppers in all the jetty maven http2 examples i have seen to date.  this project doesn't demonstrate a method of launching http2 at all

**Comment by AndreasKl** [comment]
Maybe you did not follow the instructions to setup ALPN:
`
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Xbootclasspath/p:alpn-boot-8.1.13.v20181017.jar ... net.andreaskluth.Application
`

As you can clearly see from my logs h2 is activated. Are you using JDK8 and did you select the appropriate ALPN lib for your bootclasspath?

`
INFO:oejs.Server:main: jetty-9.3.7.v20160115
INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@2d554825{/,null,AVAILABLE}
2019-01-24 08:35:22.146:INFO:oejus.SslContextFactory:main: x509=X509@35fb3008(jetty,h=[],w=[]) for SslContextFactory@7225790e(file:///home/andreas/sc/embedded-jetty-http2/target/classes/keystore,null)
INFO:oejs.ServerConnector:main: Started ServerConnector@47a76ffa{SSL,[ssl, alpn, h2, h2-17, h2-16, h2-15, h2-14, http/1.1]}{0.0.0.0:8443}
INFO:oejs.Server:main: Started @1408ms
INFO:na.Application:main: Press any key to stop Jetty.
`

![screenshot from 2019-01-24 08-39-20](https://user-images.githubusercontent.com/1105899/51662352-d6829580-1fb3-11e9-8fd3-2e1bad995b35.png)

**Comment by AndreasKl** [comment]
10 days without feedback, closing. Please reopen if you still have issues with http2.

**Comment by jnorthrup** [comment]
i will leave this closed, however embedded http/2 has been whackamole in my experience without a lot of example permutations to draw from.  my SO points are apparently beneath what i need for questions but maybe when my 6 month purgatory ends i will hoist this comment to SO... but here goes... perhaps you know where some more examples are hiding  

i'll break it down:

using embedded bootstrapping on oracle-jdk 11 turned out to be easier than tracing down a certain combination of reflection bug compatible ALPN on openjdk for me.  

i do not have a maven-based jtty runner however i use dependency plugin to dump the build classpath into target/lib and a shellscript 

```bash
#!/usr/bin/env bash
set -x

[[ -e ../pwa/target/prezip ]] || {

set -x

mkdir -p ../pwa/target/

rsync -hPa --delete  ../pwa/src/hnpwa-mobileelements-pagination/www/. ../pwa/target/prezip
gzip -v9 -r --keep  ../pwa/target/prezip
} 
 java  -classpath "./target/*:./target/lib/*" id.kbr.prime.AppKt ../pwa/target/prezip
```


using programmatic construction without web.xml   i found can have
 * http/2 *push* with static+welcomefiles  using a resourcehandler
 * http/2 *push* with static and custom API  using defaultservlet after api
 * http/2 *fetch-only* with static and custom API while specifying welcomefiles

testing port 80 for 0x22 Magic character and redirecting to https is also desirable but unclear 

i tried to infer the usecase from the jetty docs to achive welcomefiles+gzip+custom api+static+push.  so far i can live without push but its really a key feature of h2...  i find kotlin".apply" helps append initializers and reduce the symbolsto keep track of, below...



```kotlin
  
class JettyStarter( vararg val args: String) : AutoCloseable {
        val config: HttpConfiguration = HttpConfiguration().apply {
        secureScheme = "https"
        securePort = SSL_PORT
        sendXPoweredBy = false
        sendServerVersion = false
        addCustomizer(SecureRequestCustomizer())
    }

    private val server: Server = Server().apply {
                val httpFactory = HttpConnectionFactory(config)
                val http2Factory = HTTP2ServerConnectionFactory(config)
                val alpn1 = ALPNServerConnectionFactory().apply {
                    defaultProtocol = httpFactory.protocol
                }
                requestLog = AsyncNCSARequestLog()
                addConnector(
                        ServerConnector(this, SslConnectionFactory(SslContextFactory().apply {
                            keyStorePath = JettyStarter::class.java.getResource("/keystore").toExternalForm()
                            setKeyStorePassword("changeit")
                            cipherComparator = HTTP2Cipher.COMPARATOR
                            isUseCipherSuitesOrder = true
                        }, alpn1.protocol),
                                        alpn1,
                                        http2Factory,
                                        httpFactory
                        ).apply { port = SSL_PORT })

                handler = GzipHandler().apply {
                    handler = ContextHandlerCollection(

                            ContextHandler().apply {
                                contextPath = "/"
                                handler = ResourceHandler().apply {
                                    welcomeFiles = arrayOf("index.html")
                                    baseResource = Resource.newResource(
                                            args.firstOrNull() ?: AdapterServlet.resourceBase.toString())

                                }
  //TODO: repair http2 PUSH
 // where do I slip this in?  i get some interface mismatches or runtime explosions when trying to apply filter
//                                this.servletContext.addFilter("push", PushCacheFilter::class.java).apply { 
//                                    initParameters = mapOf("maxAssociations" to "32",
//                                    "ports" to Objects.toString( SSL_PORT )
//                                    )
//                                }
                              

                            },
                            ServletContextHandler().apply {
                                addServlet(AdapterServlet::class.java, "/*")
                            }

                    )
                }

            }

    /**
     *
     */
    @Throws(Exception::class)
    fun start() {
        server.start()
    }

    /**
     *
     */
    @Throws(Exception::class)
    override fun close() {
        server.stop()
    }

    
}
```
